/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
        // This is a number 0O
        // And also here is this
        // Il 
    }
}
